spring:
  application:
    name: foursales
    version: @project.version@
  jackson:
    time-zone: America/Sao_Paulo
  jpa:
    enabled: true
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  flyway:
    user: foursales
    password: 1234
    locations: classpath:db/migration
    table: FLYWAY_SCHEMA_HISTORY
    schemas: foursales
  datasource:
    url: jdbc:mysql://localhost:3306/foursales?TimeZone=America/Sao_Paulo
    username: foursales
    password: 1234

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  public:
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvDs+NrXxFOsKw8MBF+PG
      2zyYXaMSgtOVK9bJ8EDqc04EhHFNaxAsh82R+Cq7Iu8snYUIDlIYO8GAJm2a1VdJ
      OyUuVCHpFCujilCcxLSqeuIh5/Io1IGQ5xKhrxjhx+mozGiyuuMVC8QEEJzOyiAa
      UQmGk4l5l4PyGZOTZNg+gZaOSZMLRXheyyL1Gm5hIK95XfRUdoqPbluUWDttQYaS
      1XfjpP2Oo6SOhBXRsw28ICnhijKbogK3aAR2UutVeY+WZnJwYMZWvFAX5se1oa1C
      RWuAY12Ja1wBORW79gyOwYgf3bbuLr2kVVN6mlmjzWElyk4ElaC3FA1NxMT8Glz+
      6QIDAQAB
      -----END PUBLIC KEY-----


  private:
    key: classpath:private.key