spring:
  application:
    name: foursales
  jackson:
    time-zone: America/Sao_Paulo
  jpa:
    enabled: true
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  flyway:
    user: foursales
    password: 1234
    locations: classpath:db/migration
    table: FLYWAY_SCHEMA_HISTORY
    schemas: foursales

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/foursales?TimeZone=America/Sao_Paulo
    username: foursales
    password: 1234

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  flyway:
    user: ${USER_DB}
    password: ${PASSWORD_DB}
server:
  port: ${PORT}